"""
Canonical 66-book structure. osis_code matches the standard used by OSHB, MorphGNT,
and most Bible APIs, so downstream seed scripts can join on it directly.
chapter_count is used only for sanity-checking imports (e.g. flag if a source has
a different chapter count than expected).
"""

BOOKS = [
    # (order, testament, osis_code, name_en, chapter_count)
    (1, "old", "Gen", "Genesis", 50),
    (2, "old", "Exod", "Exodus", 40),
    (3, "old", "Lev", "Leviticus", 27),
    (4, "old", "Num", "Numbers", 36),
    (5, "old", "Deut", "Deuteronomy", 34),
    (6, "old", "Josh", "Joshua", 24),
    (7, "old", "Judg", "Judges", 21),
    (8, "old", "Ruth", "Ruth", 4),
    (9, "old", "1Sam", "1 Samuel", 31),
    (10, "old", "2Sam", "2 Samuel", 24),
    (11, "old", "1Kgs", "1 Kings", 22),
    (12, "old", "2Kgs", "2 Kings", 25),
    (13, "old", "1Chr", "1 Chronicles", 29),
    (14, "old", "2Chr", "2 Chronicles", 36),
    (15, "old", "Ezra", "Ezra", 10),
    (16, "old", "Neh", "Nehemiah", 13),
    (17, "old", "Esth", "Esther", 10),
    (18, "old", "Job", "Job", 42),
    (19, "old", "Ps", "Psalms", 150),
    (20, "old", "Prov", "Proverbs", 31),
    (21, "old", "Eccl", "Ecclesiastes", 12),
    (22, "old", "Song", "Song of Solomon", 8),
    (23, "old", "Isa", "Isaiah", 66),
    (24, "old", "Jer", "Jeremiah", 52),
    (25, "old", "Lam", "Lamentations", 5),
    (26, "old", "Ezek", "Ezekiel", 48),
    (27, "old", "Dan", "Daniel", 12),
    (28, "old", "Hos", "Hosea", 14),
    (29, "old", "Joel", "Joel", 3),
    (30, "old", "Amos", "Amos", 9),
    (31, "old", "Obad", "Obadiah", 1),
    (32, "old", "Jonah", "Jonah", 4),
    (33, "old", "Mic", "Micah", 7),
    (34, "old", "Nah", "Nahum", 3),
    (35, "old", "Hab", "Habakkuk", 3),
    (36, "old", "Zeph", "Zephaniah", 3),
    (37, "old", "Hag", "Haggai", 2),
    (38, "old", "Zech", "Zechariah", 14),
    (39, "old", "Mal", "Malachi", 4),
    (40, "new", "Matt", "Matthew", 28),
    (41, "new", "Mark", "Mark", 16),
    (42, "new", "Luke", "Luke", 24),
    (43, "new", "John", "John", 21),
    (44, "new", "Acts", "Acts", 28),
    (45, "new", "Rom", "Romans", 16),
    (46, "new", "1Cor", "1 Corinthians", 16),
    (47, "new", "2Cor", "2 Corinthians", 13),
    (48, "new", "Gal", "Galatians", 6),
    (49, "new", "Eph", "Ephesians", 6),
    (50, "new", "Phil", "Philippians", 4),
    (51, "new", "Col", "Colossians", 4),
    (52, "new", "1Thess", "1 Thessalonians", 5),
    (53, "new", "2Thess", "2 Thessalonians", 3),
    (54, "new", "1Tim", "1 Timothy", 6),
    (55, "new", "2Tim", "2 Timothy", 4),
    (56, "new", "Titus", "Titus", 3),
    (57, "new", "Phlm", "Philemon", 1),
    (58, "new", "Heb", "Hebrews", 13),
    (59, "new", "Jas", "James", 5),
    (60, "new", "1Pet", "1 Peter", 5),
    (61, "new", "2Pet", "2 Peter", 3),
    (62, "new", "1John", "1 John", 5),
    (63, "new", "2John", "2 John", 1),
    (64, "new", "3John", "3 John", 1),
    (65, "new", "Jude", "Jude", 1),
    (66, "new", "Rev", "Revelation", 22),
]
